apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../production

patches:
- path: patches/hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: webserver
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: patrick-evers
- target:
    kind: Certificate
    name: patrick-evers
  path: patches/certificate.yaml