name: Release Docker Image

on:
  push:
    tags:
      - 'v*'
env:
  DOCKER_IMAGE_NAME: website
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Release
      run: |
        gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name }}" --generate-notes

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Tag and push Docker image with release name
      run: |
        GIT_HASH=$(git rev-parse --short HEAD)
        docker pull ghcr.io/${{ github.actor }}/${DOCKER_IMAGE_NAME}:${GIT_HASH}
        docker tag ghcr.io/${{ github.actor }}/${DOCKER_IMAGE_NAME}:${GIT_HASH} ghcr.io/${{ github.actor }}/${DOCKER_IMAGE_NAME}:${{ github.ref_name }}
        docker push ghcr.io/${{ github.actor }}/${DOCKER_IMAGE_NAME}:${{ github.ref_name }}